Разметка всех страниц
htmlacademy-adaptive/547955-cat-energy-22 pull request #3
Opened 2021-03-28 14:45 UTC by Asiia56

Сделала разметку главной страницы, а также страницы формы и каталога

2021-03-29 09:49 UTC, pndparade requested changes

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +        <h2 class="sectionHeader">Функциональное питание для котов</h2>
Как будешь стилизовать этот заголовок относительно секции?

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +        <img class="promo__background" src="img/index-background-desktop_2.jpg" width="320" height="302" alt="final beneficiary" />
Не торопимся, разметку пока что делаем только для мобильного, учимся работать по принципу progressive enhancement. Плюс обрати внимание на то, относятся ли эти картинки к контенту. См. статью: https://htmlacademy.ru/blog/boost/frontend/content-or-decor-img

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +        <a href="#" class="promo__btn">Подобрать программу</a>
как будешь стилизовать кнопку? Обрати внимание, этот элемент повторяется и на других страницах.

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +          <img src="img/cat_back_1.png" width="50" height="53" alt="slim cat" />
по критериям Академии, эти картинки скорее тоже декоративный элемент, в разметку не выносим, используем стили.

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +        <article class="optionSlim">
для чего optionSlim? Может быть сделать универсальное название для обоих блоков?

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +            <img class="featuresList__itemImage" src="img/how_list/icon_leaf.png" width="30" height="32" alt="icon_leaf" />
тоже декоративные элементы. Плюс картинки на макете векторные, значит, используем формат svg

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +        <ul class="example__list">
Если хочешь использовать тэг списка, на мой взгляд, будет лучше dl, здесь очень похоже на список определений. Либо вообще отказаться от списка и сделать div с нужными классами. Это не будет ошибкой.

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +            <img class="example__present" src="img/after-mobile_1.jpg" width="251" height="240" alt="Boris is" />
здесь можно выбрать универсальное название, например, example__img, ведь было и стало по сути - одинаковые блоки.

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +  </footer>
А вот здесь обрати внимание на другие макеты, как будет потом перестроение и группировка элементов. Где лучше поставить .container и нужны ли дополнительные обертки для элементов

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +          <li> <a href="#" class="socialBtn">
посмотри рекомендации по оформлению социконок https://htmlacademy.ru/blog/boost/frontend/content-or-decor-img

2021-03-29 09:49 UTC, pndparade commented on source/index.html
> +          <li class="example__list__item"> 5 КГ <br /> <span>снижение веса</span> </li>
По БЭМ у элемента не может быть элемента. Два двойных подчеркивания не допустимо.

2021-03-29 13:54 UTC, Asiia56 commented on source/index.html
> +        <h2 class="sectionHeader">Функциональное питание для котов</h2>
Заголовок h1 или h2?

2021-03-29 13:56 UTC, Asiia56 commented on source/index.html
> +        <img class="promo__background" src="img/index-background-desktop_2.jpg" width="320" height="302" alt="final beneficiary" />
В плане? Разметка и сделана для мобильного. Название картинке с постфиксом -desktop дано в макета в Фигме, я его не меняла

2021-03-29 14:06 UTC, Asiia56 commented on source/index.html
> +        <ul class="example__list">
Не понимаю, как решить использую дивы: <div> <div>5 КГ</div> снижение веса </div>?

2021-03-30 09:27 UTC, pndparade commented on source/index.html
> +    <a class="page__logo--img"><img src="img/logo-mobile.jpg" width="34" height="38" alt="Кэт энерджи" /> </a>
logo сохраняем в формате svg

2021-03-30 09:41 UTC, pndparade requested changes

2021-03-30 09:41 UTC, pndparade commented on source/index.html
> +        <a href="#" class="btn-order">Подобрать программу</a>
лучше называть класс без привязки к функционалу .btn-order - это именно кнопка заказа. А если просто отправка формы? или ссылка на что-то в виде кнопки?

2021-03-30 09:41 UTC, pndparade commented on source/index.html
> +        <ol class="features-list">
думаю, тут нумерация ни к чему, просто ul, а не ol

2021-03-30 09:41 UTC, pndparade commented on source/index.html
> +            <img class="features-list__item-image" src="img/how_list/icon_leaf.png" width="30" height="32" alt="icon_leaf" />
Здесь решила оставить картинки? Не думаешь, что лучше вынести их в декор и стилизовать через стили?

2021-03-30 09:41 UTC, pndparade commented on source/index.html
> +          <li> <a href="#" class="social-btn social-btn--vk"> <span class="visually-hidden">Вконтакте</span> </a> </li>
Думаю, сами иконки это всё-таки часть Блока social-list, а не отдельные самостоятельные блоки. Но на твоё усмотрение.

2021-03-30 09:41 UTC, pndparade commented on source/index.html
> +      <p> HTML Academy </p>
Если посмотришь на другие разрешения, лого и текст - единая сущность и стоит её сделать единой ссылкой.

2021-03-30 09:51 UTC, pndparade requested changes

2021-03-30 09:51 UTC, pndparade commented on source/form.html
> +    <h2 class="form-header">Подбор программы</h2>
Это новая страница, соответственно, у неё будет другой Заголовок - именно Подбор программы. H1 будет виден в этом случае.

2021-03-30 09:51 UTC, pndparade commented on source/form.html
> +    <h2 class="form-header">Подбор программы</h2>
form-header form-intro не тянут на самостоятельные Блоки, это скорее Элементы. Продумай этот момент

2021-03-30 09:51 UTC, pndparade commented on source/form.html
> +      <fieldset class="basicInfo fieldset">
забыли убрать camelCase

2021-03-30 09:51 UTC, pndparade commented on source/form.html
> +      <fieldset class="fieldset about-cat">
about-cat add-form - тоже вряд ли независимые блоки, посмотри, как лучше их включить в выбранный тобой общий блок.

2021-03-30 09:51 UTC, pndparade commented on source/form.html
> +      <button class="form-submit btn-order">отправить заявку</button>
писала на главной странице про класс кнопки - не привязываемся к функционалу, который может меняться. btn или button будет достаточно.

2021-03-30 09:59 UTC, pndparade requested changes

2021-03-30 09:59 UTC, pndparade commented on source/catalog.html
> +      <h2 class="catalog-header">Каталог продукции</h2>
Это должно быть главным заголовком страницы. catalog-header - независимый блок?

2021-03-30 09:59 UTC, pndparade commented on source/catalog.html
> +        <li class="goods-list__item">
Проверь, учла ли ты, как будешь делать раскладку элементов по макету в блоке товара

2021-03-30 09:59 UTC, pndparade commented on source/catalog.html
> +          <h2 class="goods-list__header">Показать еще 100500 товаров</h2>
Это не тянет на заголовок, просто описание действия пользователя

2021-03-30 09:59 UTC, pndparade commented on source/catalog.html
> +      <h2 class="catalogHeader">Дополнительные товары</h2>
именование. И вопрос - откуда класс? назначение? Это независимый блок именно в рамках каталога?

2021-03-30 09:59 UTC, pndparade commented on source/catalog.html
> +            <h3 class="add-goods-list__header">Сахарозаменитель</h3>
не заголовок, просто имя товара. И лучше вынести вне dl

2021-03-30 09:59 UTC, pndparade commented on source/catalog.html
> +      <div class="catalogGift">
именование.

2021-03-30 18:32 UTC, merged